# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a389eabd27357c2aba9d427fab43441523799711002c7c8ad33f6f26f2e57a915b1147847bc766439626a07f70c28f5272bc9e06dd941b8ae625e2a8f53411e

test:
  secret_key_base: 999cb775fa0fd749f0476d0b36d0f2fa168542af2d0af21ac4a19951b57848d5d6b8b38b8a73135e49ba3d40f0fdc28d9e5e86ebcc909b9d8d7cb8f3cefed884

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
